# Week 4

Quiz1: Simulate two neural networks with swapped thetas

In [1]:
function g = sigmoid(z)
%SIGMOID Compute sigmoid function
%   g = SIGMOID(z) computes the sigmoid of z.

    % The function should also work on scalar *and* matrix values 
    g = zeros(size(z));
    
    g = 1 ./ ( 1 + exp(-z));
end

In [2]:
x = [1, 1, 2]'

x =

   1
   1
   2



In [3]:
theta1 = [1, 1, 2.4; 1., 1.7, 3.2]

theta1 =

   1.0000   1.0000   2.4000
   1.0000   1.7000   3.2000



In [4]:
a2 = [1; sigmoid(theta1*x)]

a2 =

   1.00000
   0.99889
   0.99989



In [5]:
theta2 = [1, 0.3, -1.2]

theta2 =

   1.00000   0.30000  -1.20000



In [6]:
a3 = sigmoid(theta2*a2)

a3 =  0.52493


In [7]:
theta1_new = [1., 1.7, 3.2; 1, 1, 2.4 ]

theta1_new =

   1.0000   1.7000   3.2000
   1.0000   1.0000   2.4000



In [8]:
a2_new = [1; sigmoid(theta1_new*x)]

a2_new =

   1.00000
   0.99989
   0.99889



In [9]:
theta2_new = [1, -1.2, 0.3]

theta2_new =

   1.00000  -1.20000   0.30000



In [10]:
a3_new = sigmoid(theta2_new * a2_new)

a3_new =  0.52493
