# Working with Data

## Defining matrices and vectors
In Octave or Mathlab, matrices are important first class concepts.
Matrices can be defined and assigned to variables easily, e.g. by specifying them as a set of rows.

In [1]:
A=[16 2 3 13 ; 5 11 10 8 ; 9 7 6 12 ; 4 14 15 1]

A =

   16    2    3   13
    5   11   10    8
    9    7    6   12
    4   14   15    1



Accessing cells of a matrix is straight forward:

In [2]:
A(1,1)
A(3,4)

ans =  16
ans =  12


Using the ':' syntax, we can easily work with parts of matrices. In the following example, we copy all rows from matrix A, but from these rows, we only copy columns 1 to 2.

In [3]:
B1 = A(:, 1:2)

B1 =

   16    2
    5   11
    9    7
    4   14



Here, we only copy rows 3 to 4 and columns 1 to 2.

In [4]:
B2 = A(3:4, 1:2)

B2 =

    9    7
    4   14



In Mathlab and Octave, indices start with 1, so the following code does not work correctly:

In [5]:
B4 = A(0:4, 0:2)

error: A(0,_): subscripts must be either integers 1 to (2^63)-1 or logicals


A vector is a special case of a matrix.

In [6]:
k = [1, 2, -1, -2]'

k =

   1
   2
  -1
  -2



## Computing with matrices and vectors
Let's start with a very simple matrix multiplication. This is a naive implementation:

In [7]:
v = zeros(4, 1);
for i = 1:4
  for j = 1:4
    v(i) = v(i) + A(i, j) * k(j);
  end
end
v

v =

   -9
    1
   -7
   15



Ocatve and Mathlab have powerful functions (and operators) that directly work with matrices.

In [8]:
v = A * k

v =

   -9
    1
   -7
   15



In [9]:
v = k'* A

v =

    9  -11  -13   15



In [10]:
v = Ax

error: 'Ax' undefined near line 1 column 5


In [11]:
v = sum(A*k)

v = 0


Examples for working with vectors:

In [12]:
v = [1, 2, 3, 4, 5, 6, 7]'

v =

   1
   2
   3
   4
   5
   6
   7



In [13]:
w = [1, 2, 3, 4, 5, 6, 7]'

w =

   1
   2
   3
   4
   5
   6
   7



In [14]:
z = 0;
for i = 1:7
  z = z + v(i) * w(i);
end
z

z =  140


In [15]:
z = sum(v .* w)

z =  140


In [16]:
z = w' * v

z =  140


In [17]:
z = v * w'

z =

    1    2    3    4    5    6    7
    2    4    6    8   10   12   14
    3    6    9   12   15   18   21
    4    8   12   16   20   24   28
    5   10   15   20   25   30   35
    6   12   18   24   30   36   42
    7   14   21   28   35   42   49



In [18]:
z = w * v'

z =

    1    2    3    4    5    6    7
    2    4    6    8   10   12   14
    3    6    9   12   15   18   21
    4    8   12   16   20   24   28
    5   10   15   20   25   30   35
    6   12   18   24   30   36   42
    7   14   21   28   35   42   49



Compare the following cell-based computations with their matrix-based counterparts:

In [19]:
X = rand (7,7)
for i = 1:7
  for j = 1:7
    A(i, j) = log(X(i, j));
    B(i, j) = X(i, j) ^ 2;
    C(i, j) = X(i, j) + 1;
    D(i, j) = X(i, j) / 4;
  end
end


X =

   0.090808   0.988535   0.053331   0.932615   0.264483   0.890509   0.207041
   0.018652   0.206447   0.640050   0.207878   0.462292   0.559737   0.995218
   0.357157   0.628127   0.188228   0.061904   0.406684   0.063963   0.209684
   0.131514   0.510023   0.508671   0.107032   0.389136   0.643710   0.264010
   0.976689   0.250221   0.467897   0.229077   0.492010   0.680789   0.069117
   0.588139   0.226239   0.803113   0.760182   0.430941   0.890411   0.645419
   0.977727   0.652199   0.637394   0.135624   0.131086   0.019639   0.258404



In [20]:
A
A2 = log(X)

A =

 Columns 1 through 6:

  -2.3990111  -0.0115308  -2.9312396  -0.0697631  -1.3299793  -0.1159621
  -3.9818037  -1.5777103  -0.4462082  -1.5708027  -0.7715577  -0.5802880
  -1.0295807  -0.4650127  -1.6701039  -2.7821759  -0.8997176  -2.7494516
  -2.0286432  -0.6732996  -0.6759544  -2.2346242  -0.9438259  -0.4405077
  -0.0235871  -1.3854109  -0.7595072  -1.4736990  -0.7092567  -0.3845035
  -0.5307928  -1.4861619  -0.2192598  -0.2741979  -0.8417831  -0.1160721
  -0.0225248  -0.4274062  -0.4503674  -1.9978696  -2.0318981  -3.9302627

 Column 7:

  -1.5748384
  -0.0047936
  -1.5621528
  -1.3317675
  -2.6719601
  -0.4378561
  -1.3532321

A2 =

 Columns 1 through 6:

  -2.3990111  -0.0115308  -2.9312396  -0.0697631  -1.3299793  -0.1159621
  -3.9818037  -1.5777103  -0.4462082  -1.5708027  -0.7715577  -0.5802880
  -1.0295807  -0.4650127  -1.6701039  -2.7821759  -0.8997176  -2.7494516
  -2.0286432  -0.6732996  -0.6759544  -2.2346242  -0.9438259  -0.4405077
  -0.0235871  -1.3854109  -0.759507

In [21]:
B
B2 = X^2

B =

 Columns 1 through 6:

   0.00824604   0.97720224   0.00284418   0.86977026   0.06995112   0.79300627
   0.00034790   0.04262047   0.40966461   0.04321336   0.21371426   0.31330569
   0.12756091   0.39454371   0.03542960   0.00383206   0.16539228   0.00409126
   0.01729589   0.26012339   0.25874589   0.01145592   0.15142697   0.41436200
   0.95392113   0.06261053   0.21892754   0.05247607   0.24207360   0.46347305
   0.34590690   0.05118423   0.64499062   0.57787612   0.18571050   0.79283177
   0.95595006   0.42536294   0.40627102   0.01839385   0.01718366   0.00038567

 Column 7:

   0.04286598
   0.99045869
   0.04396745
   0.06970139
   0.00477711
   0.41656527
   0.06677248

B2 =

   1.15287   1.20568   2.09288   1.15892   1.40664   2.21497   1.90654
   2.01525   1.46050   1.65953   0.78856   1.04069   1.13958   1.04880
   0.75935   0.88553   0.86331   0.65216   0.74062   1.05946   0.87846
   1.23399   1.02459   1.35097   0.88590   1.02255   1.34730   1.18031
   1.23911   1.75

In [22]:
C
C2 = X + 1

C =

   1.0908   1.9885   1.0533   1.9326   1.2645   1.8905   1.2070
   1.0187   1.2064   1.6401   1.2079   1.4623   1.5597   1.9952
   1.3572   1.6281   1.1882   1.0619   1.4067   1.0640   1.2097
   1.1315   1.5100   1.5087   1.1070   1.3891   1.6437   1.2640
   1.9767   1.2502   1.4679   1.2291   1.4920   1.6808   1.0691
   1.5881   1.2262   1.8031   1.7602   1.4309   1.8904   1.6454
   1.9777   1.6522   1.6374   1.1356   1.1311   1.0196   1.2584

C2 =

   1.0908   1.9885   1.0533   1.9326   1.2645   1.8905   1.2070
   1.0187   1.2064   1.6401   1.2079   1.4623   1.5597   1.9952
   1.3572   1.6281   1.1882   1.0619   1.4067   1.0640   1.2097
   1.1315   1.5100   1.5087   1.1070   1.3891   1.6437   1.2640
   1.9767   1.2502   1.4679   1.2291   1.4920   1.6808   1.0691
   1.5881   1.2262   1.8031   1.7602   1.4309   1.8904   1.6454
   1.9777   1.6522   1.6374   1.1356   1.1311   1.0196   1.2584



In [23]:
D
D2 = X / 4

D =

 Columns 1 through 6:

   0.0227019   0.2471338   0.0133327   0.2331537   0.0661207   0.2226272
   0.0046630   0.0516118   0.1600126   0.0519696   0.1155731   0.1399343
   0.0892892   0.1570318   0.0470569   0.0154759   0.1016711   0.0159907
   0.0328785   0.1275057   0.1271677   0.0267581   0.0972840   0.1609274
   0.2441722   0.0625552   0.1169742   0.0572691   0.1230024   0.1701971
   0.1470346   0.0565598   0.2007783   0.1900454   0.1077354   0.2226028
   0.2444317   0.1630496   0.1593485   0.0339060   0.0327716   0.0049096

 Column 7:

   0.0517603
   0.2488045
   0.0524210
   0.0660026
   0.0172792
   0.1613547
   0.0646009

D2 =

 Columns 1 through 6:

   0.0227019   0.2471338   0.0133327   0.2331537   0.0661207   0.2226272
   0.0046630   0.0516118   0.1600126   0.0519696   0.1155731   0.1399343
   0.0892892   0.1570318   0.0470569   0.0154759   0.1016711   0.0159907
   0.0328785   0.1275057   0.1271677   0.0267581   0.0972840   0.1609274
   0.2441722   0.0625552   0.116974